### ISSUE TITLE
Image.fromarray

### ISSUE THREAD

**Issue by ka1219** [Harry-icl/M2R-Julia-Sets#1]
I think `Image.fromarray` takes the element at `[0,0]` to be the top left corner of the image.

https://github.com/Harry-icl/M2R-Julia-Sets/blob/91ef45f015d5a2df433a8ef4c4c52c612f4dbf81/src/julia/map.py#L256-L262

The loop here starts at the bottom left corner of the window, so the resulting image is a reflection across the x-axis.

**Comment by ka1219** [comment]
It also seems to also be the case that `Image.fromarray` indexes in column-major order.

**Comment by Harry-icl** [comment]
Thanks for pointing out, I've fixed the column-major order already in my branch, but will fix the reflection in the x axis issue now.

**Comment by Harry-icl** [comment]
Fixed the reflection issue in the draw_mandelbrot and draw_julia functions with a [::-1] index
